### ISSUE TITLE
MQTT and GPS plugins not available on F-Droid

### ISSUE THREAD

**Issue by camsellem** [fr3ts0n/AndrOBD#167] opened 2021-07-26 08:39 UTC
Hi,

I can't find the plugins for the GPS Sensor and the MQTT Publisher. Were they discontinued?  Thanks

![image](https://user-images.githubusercontent.com/3879044/126959868-2e3fe86a-ead8-4524-be9d-46a9298ff75f.png)

**Comment by fr3ts0n** [comment] 2021-07-28 18:32
Yes, I know, there is a problem with the metadata links (icons and descriptions) on fdroid web site.

There are all available extension packages listed with identical description / icon.
If you mouseover each package ypu will find each entry to link to a different apk:
- gps provider
- mqtt publisher
- sensor provider

So you can download the desired apk, but currently you will have to trace through the different links.

**Comment by aha999** [comment] 2021-08-21 09:03
This is really confusing also for me... If this is caused by metadata links, I think AndrOBD should change to Organization on Github and have separate repos for every plugin. It would also sort other things out nicely... Like if for example in the future AndrOBD gets ported to iOS or other devices, they could be easily findable under AndrOBD organization :)

**Comment by fr3ts0n** [comment] 2021-09-12 16:26
Fixed on F-Droid:
![image](https://user-images.githubusercontent.com/2822578/132995288-1a7d079f-aeb4-469d-b878-3b4894beadb0.png)

**Closed by fr3ts0n** 2021-09-12 16:26 UTC
