### ISSUE TITLE
Connected but no data is displayed in the app

### ISSUE THREAD

**Issue by cfabio** [fr3ts0n/AndrOBD#71] opened 2019-02-02 18:39 UTC
I am trying to use this app to get data from my car using a Vgate iCar 2 ELM327 WiFi OBD2 device.  
It connects just fine but then nothing appears in the app, if I click in the menu on "get OBD data", "OBD vehicle info" or anything else I only get blank pages.  
Any clue on how I can make this work?  

Edit: I tried debugging with logcat but there is literally nothing interesting in the log even I select the most verbose logging option.

**Comment by cfabio** [comment] 2019-02-02 21:37
I missed that part or the wiki.  
He is the log, there are indeed a few errors reported in the logs: [AndrOBD.log.4.txt](https://github.com/fr3ts0n/AndrOBD/files/2824886/AndrOBD.log.4.txt)

**Comment by fr3ts0n** [comment] 2019-02-02 22:16
Thanks for the log.
Based on your log file, your problem looks very similar to the report of issue #70 (which I haven't received any details / log yet)
It appears that you also use WIFI Elm adapter on Android 9.

Now that I have some details on this, I'll check into that.

**Comment by cfabio** [comment] 2019-02-03 09:38
The phone I am trying this on actually runs lineageos 15.1 which is android 8.1.0

**Comment by fr3ts0n** [comment] 2019-02-03 10:59
I don't have any V8.1 / V9 Hardware device yet, but I could reproduce the problem with android V9 emulator. 

Here is a test version for you to verify the fix:
https://t.me/AndrOBD_dev/212

Please let me know if this works for you

**Comment by cfabio** [comment] 2019-02-03 11:56
Could you please attach the file to this post?
I don't have telegram.

**Comment by cfabio** [comment] 2019-02-03 12:34
Thanks for the link.
I don't seem to be able to manually install this APK though, it tells me "App not installed".

**Comment by fr3ts0n** [comment] 2019-02-03 12:52
Oh, yes, this is a debug version of the app, which does not contain any signature by the issuer (FDroid). 
Therefore you will have to remove the original F-Droid app before you can install the test version.

You may also have to allow installation of apps from other sources to get it installed.

**Comment by fr3ts0n** [comment] 2019-02-03 13:05
PS: there is a FOSS version of telegram available on FDroid, which is a really good alternative to  WhatsApp because it allows to use multiple clients (Mobile, Tablet, PC) on the same account simultaneously.
(https://f-droid.org/de/packages/org.telegram.messenger/)

It's quite handy to exchange app versions, and report comments this way ...

**Comment by cfabio** [comment] 2019-02-03 15:51
I couldn't install the app from the phone itself but running `adb install -t app.apk` did the trick.
I can also confirm that @fr3ts0n fixed the issue, now I can connect to the device and get all kind of data from the ECU.
Look forward to having the fix pushed to fdroid.

**Comment by fr3ts0n** [comment] 2019-02-03 16:54
Fixed, released with V2.0.6

**Closed by fr3ts0n** 2019-02-03 16:54 UTC
