### ISSUE TITLE
Mode 09 PID 00  ISO Standard is different

### ISSUE THREAD

**Issue by Artur-debug** [fr3ts0n/AndrOBD#174] opened 2021-09-21 21:52 UTC
In picture the blue byte should be a Message_Counter_Byte. AndrOBD interprets this byte as data and thinks that PIDs 08, 09, 0a, 0b, 0c are supported.
My car only supports PIDs 01, 02, 03, 04. That should be the first data byte F0 after the Message_Count_Byte. 

![screen-2021-09-21-23-36-03](https://user-images.githubusercontent.com/84518891/134251703-edad6b7b-4537-441e-adc4-d9a20e923366.png)

**Important details on your environment:**
- Android OS version 10
- AndrOBD version 2.4.2
- OBD adapter type 
- Audi A3 (8PA) 2005 2L 140PS

[Mode09PID00_ByteMisinterpretation.txt](https://github.com/fr3ts0n/AndrOBD/files/7206454/Mode09PID00_ByteMisinterpretation.txt)

**Comment by Artur-debug** [comment] 2021-09-21 22:30
![screen-2021-09-21-23-44-21](https://user-images.githubusercontent.com/84518891/134254969-f58658e3-d4ff-42dc-9c04-cef9ac2b84c6.png)

Not every PID seems to have a Message_Count_Byte. 

>0900
SEARCHING...
49 00 01 F0 00 00 00

>0901
49 01 05

>0902
49 02 01 00 00 00 xx*
49 02 02 xx xx xx xx
49 02 03 xx xx xx xx
49 02 04 xx xx xx xx
49 02 05 xx xx xx xx

*xx is Data

>0903
49 03 04

>0904
49 04 01 xx xx xx xx
49 04 02 xx xx xx xx
49 04 03 xx xx xx xx 
49 04 04 xx xx xx xx 

>0905
7F 09 12 

>0906
7F 09 12 

>0907
7F 09 12 

>0908
7F 09 12 

>0909
7F 09 12 

>090a
7F 09 12

**Comment by fr3ts0n** [comment] 2021-09-23 17:27
Thanks again for the next very clear report,

Bug confirmed!
The message count appears to be optional, probably dependent on the vehicle implementation, since I do have many cases indicating the mode 9 pid's without message count ...
However, obviously it needs to be treated optionally

I'll try to find a solution and then post a fix for your testing / verification

**Comment by fr3ts0n** [comment] 2021-09-23 20:06
Test version (V2.4.3) is now available here:
https://t.me/c/1434285001/1138

**Comment by Artur-debug** [comment] 2021-09-24 13:28
Length of VIN should be 17. Number of VIN should be 1. Length of CAL-ID should be 16 and the number of CAL-ID should be 1.

<img src="https://user-images.githubusercontent.com/84518891/134681043-495b735a-d09e-4d5f-bac5-d9c6acd376a3.jpg" width="250"/> 

[AndrOBD.log.0 (6).txt](https://github.com/fr3ts0n/AndrOBD/files/7225926/AndrOBD.log.0.6.txt)


![Untitled 1](https://user-images.githubusercontent.com/84518891/134682070-056c39a0-b194-43d3-a56d-aa67087fde6b.png)

**Comment by Artur-debug** [comment] 2021-09-24 13:42
![Untitled 1](https://user-images.githubusercontent.com/84518891/134684344-be4dea0d-0737-4be4-9f04-71d33186c0ad.png)

**Comment by Artur-debug** [comment] 2021-09-24 13:43
![Untitled 1](https://user-images.githubusercontent.com/84518891/134684507-d9be3067-1375-490a-a411-3f2b77085b21.png)

**Comment by Artur-debug** [comment] 2021-09-25 20:48
Probably the ISO standards are different.

**Comment by Artur-debug** [comment] 2021-09-26 13:59
After App-Update 0902 is not queried :

<img src="https://user-images.githubusercontent.com/84518891/134810909-bd20156d-63de-4caf-80af-64b99cfc912a.jpg" width="250"/> 


2021-09-26	15:42:59.964	FINE	com.fr3ts0n.prot	ELM rx:'>' (0900)
2021-09-26	15:42:59.965	FINE	data.ecu	01 Länge der Fahrgestellnummer (VIN)            240.0 
2021-09-26	15:42:59.966	FINE	com.fr3ts0n.prot	com.fr3ts0n.ecu.prot.obd.ElmProt@72ca631 TX:'0900'
2021-09-26	15:43:00.105	FINE	com.fr3ts0n.prot	com.fr3ts0n.ecu.prot.obd.ElmProt@72ca631 RX:'490001F0000000'
2021-09-26	15:43:00.107	FINE	com.fr3ts0n.prot	ELM rx:'490001F0000000' (0900)
2021-09-26	15:43:00.306	FINE	com.fr3ts0n.prot	com.fr3ts0n.ecu.prot.obd.ElmProt@72ca631 RX:'>'
2021-09-26	15:43:00.308	FINE	com.fr3ts0n.prot	ELM rx:'>' (0900)
2021-09-26	15:43:00.309	FINE	data.ecu	01 Länge der Fahrgestellnummer (VIN)            240.0 
2021-09-26	15:43:00.311	FINE	com.fr3ts0n.prot	com.fr3ts0n.ecu.prot.obd.ElmProt@72ca631 TX:'0900'
2021-09-26	15:43:00.448	FINE	com.fr3ts0n.prot	com.fr3ts0n.ecu.prot.obd.ElmProt@72ca631 RX:'490001F0000000'
2021-09-26	15:43:00.450	FINE	com.fr3ts0n.prot	ELM rx:'490001F0000000' (0900)
2021-09-26	15:43:00.650	FINE	com.fr3ts0n.prot	com.fr3ts0n.ecu.prot.obd.ElmProt@72ca631 RX:'>'
2021-09-26	15:43:00.652	FINE	com.fr3ts0n.prot	ELM rx:'>' (0900)
2021-09-26	15:43:00.654	FINE	data.ecu	01 Länge der Fahrgestellnummer (VIN)            240.0 
2021-09-26	15:43:00.655	FINE	com.fr3ts0n.prot	com.fr3ts0n.ecu.prot.obd.ElmProt@72ca631 TX:'0900'
2021-09-26	15:43:00.792	FINE	com.fr3ts0n.prot	com.fr3ts0n.ecu.prot.obd.ElmProt@72ca631 RX:'490001F0000000'
2021-09-26	15:43:00.794	FINE	com.fr3ts0n.prot	ELM rx:'490001F0000000' (0900)
2021-09-26	15:43:00.994	FINE	com.fr3ts0n.prot	com.fr3ts0n.ecu.prot.obd.ElmProt@72ca631 RX:'>'
2021-09-26	15:43:00.997	FINE	com.fr3ts0n.prot	ELM rx:'>' (0900)
2021-09-26	15:43:00.999	FINE	data.ecu	01 Länge der Fahrgestellnummer (VIN)            240.0 
2021-09-26	15:43:01.001	FINE	com.fr3ts0n.prot	com.fr3ts0n.ecu.prot.obd.ElmProt@72ca631 TX:'0900'
2021-09-26	15:43:01.136	FINE	com.fr3ts0n.prot	com.fr3ts0n.ecu.prot.obd.ElmProt@72ca631 RX:'490001F0000000'
2021-09-26	15:43:01.137	FINE	com.fr3ts0n.prot	ELM rx:'490001F0000000' (0900)
2021-09-26	15:43:01.338	FINE	com.fr3ts0n.prot	com.fr3ts0n.ecu.prot.obd.ElmProt@72ca631 RX:'>'
2021-09-26	15:43:01.340	FINE	com.fr3ts0n.prot	ELM rx:'>' (0900)
2021-09-26	15:43:01.341	FINE	data.ecu	01 Länge der Fahrgestellnummer (VIN)            240.0 

[AndrOBD.log.0.0101.txt](https://github.com/fr3ts0n/AndrOBD/files/7231499/AndrOBD.log.0.0101.txt)

**Comment by fr3ts0n** [comment] 2021-09-26 15:56
OK my last attempt to remove ISO string padding character did remove valuable information from PID bitmask ...
I really hate these protocol inconsistencies (i.e.: who does conditionally 0-pad a string at it's beginning?)
-> Don't let politics get involved into technical specs ;-)

**Comment by fr3ts0n** [comment] 2021-09-26 16:05
Should be fixed with this update:
https://t.me/AndrOBD_dev/240

**Comment by Artur-debug** [comment] 2021-09-26 16:38
Works fine, thank you!

**Closed** 2021-09-26 16:42 UTC
Labels: bug
