### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by monikamishra-54** [fr3ts0n/AndrOBD#224] opened 2022-12-28 07:03 UTC
# Describe the bug

Shows OBD protocol error when clicked on clear fault code.

## AndrOBD Debug log files

E/com.fr3ts0n.prot: (NRC:0x22) Conditions not correct (SVC:0x04)

## Additional context

Screenshot is attached for more reference.
[
![8c0ec638-35de-4e49-b1fa-32c4240ab83e](https://user-images.githubusercontent.com/58734760/209772113-f8013bbe-8ff8-4e09-99cd-cd011a018c92.JPG)
](url)

**Comment by fr3ts0n** [comment] 2022-12-28 08:00
This is NOT a bug in AndrOBD.
This is your car reporting that clearing fault codes is NOT allowed in current situation.
"Conditions not correct" means that not all conditions are met to perform the requested action.

Did you have your engine running while trying to clear codes?
- I know of several vehicles which don't allow this while the engine is running.

Please try to clear codes with engine OFF.

**Comment by monikamishra-54** [comment] 2022-12-29 07:08
Thank you, It worked when engine is OFF but now it shows response is pending when I clear fault code
E/com.fr3ts0n.prot: (NRC:0x78) Request correctly received  but response is pending
![Screenshot_2022-12-29-12-16-48-988_com fr3ts0n ecu gui androbd](https://user-images.githubusercontent.com/58734760/209915966-399d2fb7-4c46-47f0-b28d-82f5fc86820c.jpg)

**Comment by fr3ts0n** [comment] 2022-12-29 08:03
Could you please provide a logfile (FINE) for that?
See: https://github.com/fr3ts0n/AndrOBD/wiki/Reporting-improvements---issues#debug-log-files

**Comment by fr3ts0n** [comment] 2022-12-29 08:06
Sorry, didn't mean to close it yet ...

**Comment by monikamishra-54** [comment] 2022-12-29 10:01
Didn't have FINE log level in my android device only debug and verbose is there
![image](https://user-images.githubusercontent.com/58734760/209935156-4f738251-5d07-48fd-86d2-ad097237eeef.png)

**Comment by fr3ts0n** [comment] 2022-12-29 11:27
Your screenshot above confirms the symptom, but does not provide any details what did lead to the symptom.
Sorry, but any further analysis of this does require a log output with higher granularity.

**Closed** 2023-12-20 07:18 UTC
Labels: wait for details
